### PR TITLE
Add min_threads option

### PR DESCRIPTION
**Pull request by tagomoris**
* not to decrease/increase Jetty threads for high load environment

### CODE REVIEW

**Comment by tagomoris** [comment]
@matadon ping?

**Comment by matadon** [comment]
On Mar 23, 2015, at 14:03 , TAGOMORI Satoshi <notifications@github.com> wrote:
> 
> @matadon ping?

Buried in client work, will try to test and merge on Friday.

**Comment by tagomoris** [comment]
I see. Thank you for response :)

**Comment by matadon** [comment]
On Mar 23, 2015, at 14:03 , TAGOMORI Satoshi <notifications@github.com> wrote:
> 
> @matadon ping?

Merged today, will cut a new gem after wrapping up with the current client and merging/closing the old PRs.

**Comment by tagomoris** [comment]
Great. Thank you!

**Comment by tagomoris** [comment]
@matadon Do you have a plan to release a new version on rubygems.org?

**Comment by matadon** [comment]
On Apr 7, 2015, at 04:33 , TAGOMORI Satoshi <notifications@github.com> wrote:
> 
> @matadon Do you have a plan to release a new version on rubygems.org?

I do, but am spending this week wrapping up a project. Figure early next week.

**Comment by tagomoris** [comment]
Great news to hear :)

**Comment by tagomoris** [comment]
@matadon ping?
I'm very sorry but this is a blocker for my project now :(

**Comment by matadon** [comment]
On Apr 21, 2015, at 18:52 , TAGOMORI Satoshi <notifications@github.com> wrote:
> 
> @matadon ping?
> I'm very sorry but this is a blocker for my project now :(

Gem cut today. Let me know if there are any issues.

**Comment by tagomoris** [comment]
@matadon Thank you a lot! :sparkles:

**Comment by matadon** [comment]
On Apr 22, 2015, at 19:30 , TAGOMORI Satoshi <notifications@github.com> wrote:
> 
> @matadon Thank you a lot! 

My pleasure — should have sent that up sooner.

**Pull request merged**
